name: Kalah Backend CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: kalah

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Build kalah Backend
        run: cd kalah && mvn clean test

  build:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: kalah

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Build kalah Backend
        run: cd kalah && mvn clean -U -B package -DskipTests

      - name: Build and run the app
        run: cd kalah && docker-compose -f docker-compose.yaml up -d -V --build

      - name: Fetch Backend Status
        run: |
          sleep 10
          status=$(curl -s http://localhost:8080/actuator/health | jq -r '.status')
          retries=12

          while [[ "$status" != "UP" ]] && [[ $retries -gt 0 ]]; do
            echo "Status is '$status' - waiting 5 secs ($retries retries left)"
            sleep 5
            retries=$((retries - 1))
            status=$(curl -s http://localhost:8080/actuator/health | jq -r '.status')
          done

          echo "Final status is '$status'"
          if [[ "$status" != "UP" ]]; then
            curl -v http://localhost:8080/actuator/health || :
            docker ps || :
            docker logs kalah-app || :
            exit 1
          fi

          echo "::set-output name=STATUS::$status"
        id: healthcheck

      - name: Confirm microservice status
        if: ${{ steps.healthcheck.outputs.STATUS == 'UP' }}
        run: |
          echo "The kalah service is UP."